language: node_js
node_js:
- 13.8.0
dist: trusty
sudo: false
addons:
  ssh_known_hosts:
  - 163.172.133.90
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/deploy_rsa ~/.ssh/deploy_rsa
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
after_success:
  - npm install
  - npx webpack
  - eval "$(ssh-agent -s)" #start the ssh agent
  - cp .travis/deploy_rsa ~/.ssh/deploy_rsa
  - chmod 600 ~/.ssh/deploy_rsa
  - ssh-add ~/.ssh/deploy_rsa
  - git remote add deploy DEPLOY_REPO_URI_GOES_HERE
  - git push deploy
git:
  depth: 9999999
deploy:
- provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"

  on:
    branch: feature/travis-ci
