version: "3"
services:

 nginx:
  container_name: nginx
  build: .
  volumes:
   - ./nginx/nginx.conf:/etc/nginx/conf.d/app.conf
  ports:
   - "80:80"
   - "5000:5000"
  restart: always
  image: nginx